### ISSUE TITLE
Dart 2 Incompatible

### ISSUE THREAD

**Issue by RobMrz** [tensor-programming/flutter_location_example#2]
Thank you for the example unfortunately it seems that this plugin is no longer supported. 

"Because location_example depends on geolocation >=0.1.1 which requires SDK version <2.0.0, version solving failed."

**Comment by Sanaebadi97** [comment]
Dear Just Try it :

```
dependencies:
geolocation:
       git:
       url: https://github.com/shehabic/geolocation
```

be OKay
